### ISSUE TITLE
Organization Profile

### ISSUE THREAD

**Issue by jmbarcial** [sdcc-i-coop-portal/zoom108#19]
- updating of restrictions
- updating of members
- different restrictions for different accounts of same organization

**Comment by regiboy** [comment]
Change db structure with regards to org
* add new table (PK, acct_profile_master_no, org_sup_id)

**Comment by regiboy** [comment]
New GUI for updating:
* Integrated apm_osp table to view different ha profiles by selected org
* Upon selecting an account profile, now displays its ha profiles, with the option to add existing or new holders
* Adding existing or new holders is in a dialog, with tabs.

**Comment by regiboy** [comment]
Todo:
* New holder image
* AF (hindi na i-sasama)
* Schools will no longer be included

**Comment by regiboy** [comment]
Done:
* Insertion of image and signature for new holders

**Comment by regiboy** [comment]
Validation of org members / restrictions:
* bawal yung isang member lang
* if co-signer = 0 and all_co-signer > 0, set co-signer to all_co-signer

**Comment by regiboy** [comment]
Done since 2017-09-25:
* tested and used Jon's function for updating org profile (success siya)

**Comment by regiboy** [comment]
Added 2017-09-27:
* Validation of org members - should have at least one SDCC member

**Comment by regiboy** [comment]
Done on 2017-10-03:
* Images for multiple new holders successfully added.
